dunglas/symfony-docker

Dockerfile, docker-compose.yaml, docker/app/docker-entrypoint.sh
Hi,
I've seen a question about installing specific symfony version on symfony slack and thought it could be supported here.
Not sure about `VERSION` default value in compose, but we'll probably figure it out.
What do you think?
=> Support building using specific symfony version

docker-compose.yaml
Usage of this feature should be consistent with selecting specific version.
=> Pass stability from env variable to dockerfile

Dockerfile
Fix the error at "docker-compose up" by making STABILITY optional
=> Fix the STABILITY env

docker-compose.yaml
I forgot to give the target in docker-compose.yaml file after my tests
=> Fix docker-compose after all dockerfile in one

README.md
Add documentation for use xdebug, I copied the note made for api platform and adapted for this project.
Resolve #34
=> Add documentation for debugging

README.md
Added instruction to fix filesystem permissions on linux, that right after the project creation do not allow the user in the host system to write files.
Related to issue #14
=> Updated readme to include a note about linux users

README.md
Fix the error of the issue #38
=> Fixed xdebug guide

.gitattributes, .travis.yml
We can not use the docker addons because that provide a docker-compose version (1.17.1) with a bug on the variables substitution.
So I installed the docker version corrected by my self
=> Adding Travis integration

README.md
Replace the service name in docker-compose command with the correct one
=> fix service name in docker-compose command

Dockerfile
**My docker + docker-compose version**
* _docker version 18.09.3, build 774a1f4_
* _docker-compose version 1.23.1, build b02f1306_
**Steps to reproduce:**
* `git clone https://github.com/dunglas/symfony-docker.git`
* `cd symfony-docker`
* `docker-compose up`
**Result**  
```
Creating symfony-docker_app_1_3a027395d299 ... done
Creating symfony-docker_nginx_1_563b5da73158 ... done
Creating symfony-docker_h2-proxy_1_8fcfd6bfc42c ... done
Attaching to symfony-docker_app_1_2e2dbf6f980b, symfony-docker_nginx_1_d7979f7f7b06, symfony-docker_h2-proxy_1_7de1995111d1
app_1_2e2dbf6f980b | PHP Warning:  PHP Startup: Unable to load dynamic library 'intl.so' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20170718/intl.so (Error loading shared library libicui18n.so.62: No such file or directory …
```
=> Removing the warning for the PHP Intl extension

Dockerfile, docker/app/docker-entrypoint.sh
Also, fix installation of git.
=> Add the extra.symfony.docker flag

README.md
https://github.com/dunglas/symfony-docker/issues/52
Solved
=> Solution to issues/52

Dockerfile
I merge #56 fix on the wrong branch
=> Fix --with-libzip

docker/h2-proxy/default.conf
These options sould be fix the issue #59
=> Add missing proxy options

Dockerfile
- Fixes Chrome/Brave SSL issues
- Adds support to override default server name (`localhost`). Useful if running multiple sites locally.
Build:
```
docker-compose build --build-arg SERVER_NAME=myapp.local
docker-compose up
```
Host Certificate Setup (macOS):
- Add myapp.local to /etc/hosts
- Navigate to https://myapp.local
- Download self-signed certificate (`myapp.local.cer`) to, e.g., `~/Desktop`
- Run command:
```
sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain ~/Desktop/myapp.local.cer
```
Reload https://myapp.local in browser.
=> Customize Server Name + Chrome/Brave SSL Fix

README.md, docker-compose.yml
Documentation for #58 
poke @bmeynell
=> Add docs for customize server name

docker/caddy/Caddyfile
Also enables access logs and gzip compression.
=> fix: static files server configuration

docker-compose.yml, docker/php/docker-entrypoint.sh
Needs https://github.com/symfony/recipes/pull/113.
=> feat: add support for Doctrine ORM

docker-compose.yml
=> fix: DATABASE_URL env var

docs/troubleshooting.md
Adding documentation about Symfony and redirects with https protocol
Closes #68
=> Mention HTTPs redirect fix in documentation

docs/xdebug.md
Update doc to use latest version of Xdebug
=> Update doc for Xdebug 3

docker/php/docker-entrypoint.sh
Make sure the `DATABASE_URL` is checked without comments :)
=> fix: properly check for DB environment

Dockerfile, docker-compose.prod.yml, docker-compose.yml, docker/caddy/Caddyfile, docker/php/docker-healthcheck.sh, docker/php/php-fpm.d/zz-docker.conf, docs/production.md
* Prevent to use default values for sensitive env vars in production
* Don't store the content of sensitive env vars in the config
* Use a UNIX socket for performance
* Synchronize other changes recently introduced in API Platform
=> feat: synchronize with API Platform's definition

Dockerfile, docker/php/docker-entrypoint.sh
See https://github.com/api-platform/api-platform/pull/1862 and https://github.com/api-platform/api-platform/pull/1857.
=> fix: backport latest changes made in API Platform

.github/workflows/ci.yml, Dockerfile
=> fix: issue preventing Caddy to start

Dockerfile, docker/caddy/Caddyfile
Close #130. See dunglas/mercure#499.
=> fix: ensure that the latest version of Mercure and Vulcain are always used.

Dockerfile, docker/caddy/Caddyfile
Similar to https://github.com/api-platform/api-platform/pull/1888
=> fix: add Vulcain back

docker/php/docker-healthcheck.sh
Port of a change in the healthcheck introduced in https://github.com/api-platform/api-platform/pull/1887. Closes #149.
=> fix: healthcheck

docs/existing-project.md
Fixes some typos in the new docs from #156
=> Fix typos in the docs

docs/xdebug.md
I add some explanation to debug with Xdebug.
=> docs: add a section for xdebug in PHPStorm

docs/xdebug.md
Followin the [PR](#160 ) submit by @abdounikarim, I added a section to use a PHP Remote Debug server!
=> Improve Xdebug configuration documentation with PHPStorm

docker/php/php-fpm.d/zz-docker.conf
Copied from https://github.com/api-platform/api-platform/pull/1997
=> fix: set php-fpm process_control_timeout

docs/xdebug.md
Also contains various improvements.
=> docs(xdebug): fix host on Linux

Dockerfile, docker/php/conf.d/symfony.dev.ini, docker/php/conf.d/symfony.prod.ini, docker/php/docker-entrypoint.sh
Tweak PHP config according to Blackfire's recommendation.
=> feat: improve PHP config

.github/workflows/ci.yml, README.md, docker/php/docker-entrypoint.sh, docs/build.md, docs/existing-project.md, docs/makefile.md, docs/production.md, docs/troubleshooting.md, docs/xdebug.md
Follow : https://www.docker.com/blog/announcing-compose-v2-general-availability/
=> feat: Promote Compose v2

docker-compose.yml
Follows https://github.com/symfony/recipes/pull/1115
=> chore: compatibility with the new ORM recipe

docker-compose.yml, docs/production.md
=> fix: use !ChangeThisMercureHubJWTSecretKey! as default JWT secret key

Dockerfile
https://github.com/mlocati/docker-php-extension-installer
Fixes https://github.com/dunglas/symfony-docker/issues/276
=> Use php extensions installer

docs/xdebug.md
Fix: https://github.com/dunglas/symfony-docker/issues/299
=> docs: Xdebug on symfony commands

.github/workflows/ci.yml, Dockerfile, README.md
Like : https://github.com/api-platform/api-platform/pull/2253/files#diff-21ee93e31c9cec7a5f33b680622da377c451b62b6c44eac6d9550eade41beb47
=> feat: improve Dockerfile link on copy

docker/caddy/Caddyfile
https://github.com/dunglas/frankenphp/pull/79#pullrequestreview-1162649492
=> feat: rename DEBUG to CADDY_DEBUG

README.md, docker/caddy/Caddyfile, docs/tls.md, docs/troubleshooting.md
=> feat: Allow local certificates to be used by Caddy

docker/php/docker-entrypoint.sh
=> Ensure tmp folder is empty

docs/production.md
=> docs: configuring a load balancer or a reverse proxy

.github/workflows/ci.yml, Dockerfile
It's a try. We need https://github.com/hadolint/hadolint/issues/826 to get a green CI
=> Use hadolint to check dockerfile

docs/build.md
=> docs: add server name tips and custom https port note

docker-compose.override.yml
> `--watch` will watch the config file and automatically reload it after it changes. ⚠️ This feature is intended for use only in local development environments!
https://caddyserver.com/docs/command-line#caddy-run
=> Watch Caddyfile in dev env

Dockerfile
Minor change, just to keep extensions list sorted.
=> Sort prod PHP extensions alphabetically

Dockerfile
Closes https://github.com/dunglas/mercure/issues/770.
=> fix: Caddy build

docker/php/conf.d/app.dev.ini
Resolve https://github.com/dunglas/symfony-docker/issues/454
=> feat:  Change xdebug.client_host configuration for dev environments

Dockerfile, docker/caddy/Caddyfile, docker/php/docker-entrypoint.sh
Closes #465.
Include https://github.com/api-platform/api-platform/pull/2518 and https://github.com/api-platform/api-platform/pull/2517.
=> feat: better healthcheck and prevent useless composer install calls

frankenphp/conf.d/app.ini
=> fix: session support

README.md, docs/build.md, docs/production.md, frankenphp/docker-entrypoint.sh
=> Adding --detach option to the command

frankenphp/conf.d/app.dev.ini
=> fix: do not use xdebug://gateway to resolve host address

docs/build.md
Fix typos documentation for windows users
=> Fix typos documentation

compose.override.yaml, compose.prod.yaml, compose.yaml
See https://docs.docker.com/compose/compose-file/04-version-and-name/#version-top-level-element
=> chore: remove top-level version elements

docs/tls.md, frankenphp/Caddyfile
tls config should be in the domain config
=> feat: add caddy server extra

frankenphp/Caddyfile
=> feat: add Brotli compression support

README.md, docs/mysql.md
=> Add documentation on how to use MySQL instead of PostgreSQL.

README.md, docs/alpine.md
=> docs: using Alpine Linux instead of Debian

Dockerfile
=> fix: volume instruction moved for all stages

frankenphp/docker-entrypoint.sh
See https://x.com/lyrixx/status/1781315470823440705.
=> feat: use the --all-or-nothing flags for migrations

frankenphp/Caddyfile
See https://github.com/api-platform/api-platform/pull/2727 and https://github.com/dunglas/frankenphp/pull/887.
=> chore: simplify Caddyfile (Caddy 2.8)

compose.override.yaml, compose.yaml, docs/tls.md, docs/troubleshooting.md
See https://github.com/symfony/symfony/pull/37357 and https://github.com/symfony/recipes/pull/790
=> chore: remove useless trusted proxies environement variables

frankenphp/docker-entrypoint.sh
This hack is not necessary since we moved to FrankenPHP.
=> chore: remove useless public/ directory in skeleton

.editorconfig
Fix https://github.com/dunglas/symfony-docker/issues/690
=> feat: update editorconfig

docs/xdebug.md
Hello there! 
I added some VScode debug configuration instructions because I found them useful in my case. I hope this helps others as well.
=> docs: add xdebug configuration for VSCode

compose.override.yaml
See https://github.com/dunglas/symfony-docker/issues/736 for more informations about this change
=> feat: add possibility to override APP_ENV

Dockerfile, compose.override.yaml
=> chore: move Caddy file to /etc/frankenphp

docs/existing-project.md
as far as I understand, this doc was for previous version of the project, now worker seem to be included always and not disabled by such env var
=> fix(doc): worker mode
