dunglas/symfony-docker

Dockerfile
Dockerfile.h2-proxy
docker-compose.yaml
docker/app/docker-entrypoint.sh
docker/httpd/httpd.conf

Just open `https://localhost`.
* The HTTP/2 reverse proxy **is not secure** and is not suited for production usage. Prefer using CloudFlare or the reverse proxy provided by your cloud platform in production.
* Apache is used instead of Nginx as reverse proxy because Nginx doesn't support HTTP/2 Push yet bot Apache does (and this feature is present in Symfony: WebLink component)

HTTP/2 and HTTPS support

---

Dockerfile

This allows FPM to listen on all interfaces even when IPv6 is disabled so that instead of seeing this:-
```
ERROR: failed to create new listening socket: socket(): Address family not supported by protocol (97)
ERROR: FPM initialization failed
```
one should see this:-
```
NOTICE: Failed implicitly binding to ::, retrying with 0.0.0.0
NOTICE: fpm is running, pid 1
NOTICE: ready to handle connections
```
See https://github.com/docker-library/php/pull/562

Use php:7.2-fpm-alpine image

---

Dockerfile

Fix the build after installing the symfony skeleton caused by the composer auto-scripts that can not access the configuration
Example on my computer : https://ibb.co/dG70Ud

Fix the build of app with auto-script like recipe framework-bundle

---

docker/app/php.ini

`opcache.memory_consumption` is present on the [Symfony documentation](http://symfony.com/doc/current/performance.html#configure-opcache-for-maximum-performance) while `opcache.interned_strings_buffer` should be upgraded also as the default value is quite low.

Improve OPcache settings

---

Dockerfile

Flex has now the same capabilities, using it allows to speed up a bit the build.
Also clear the Composer cache after the install to reduce the image size.

Replace Prestissimo by Flex

---

README.md

Docker compose automatically merge both `docker-compose.yaml` and `docker-compose.override.yaml` files if `-f`` is not provided.
So I simplified the command and make a quick note inspired from docker compose documentation (https://docs.docker.com/compose/reference/overview/#specifying-multiple-compose-files)

Simplify docker-compose command with override file

---

Dockerfile

--with-libzip was removed with PHP 7.4 and I don't know why the build on the initial PR was green

Fix --with-libzip

---

Dockerfile

As the Docker image is now using Composer 2, this trick is not needed anymore.

Remove global Flex as it's not needed anymore with Composer 2

---

docs/troubleshooting.md

Fix #79
It's a re-open of #85.. I don't know why the conflict resolution was not updating on the origianl PR

fix: update SSL trust issue

---

docker/caddy/Caddyfile

fix `experimental_http3` deprecation (moved under `server.protocol` "namespace")

fix: experimental_http3 moved under servers.protocol

---

docker/php/docker-entrypoint.sh

Do not wait for the DB to be available if there are other errors blocking the access to it.
How to test it: 
- Create an application with a DB
- Add a PHP error in our files (controller, commands, ....)
- Restart the php container

fix: do not check DB availability if code errors

---

docker/php/docker-entrypoint.sh

feat: Try to create empty database at startup, in order to avoid the error message : "The database is not up or not reachable" if database doesnt exist.

feat: create database at startup

---

docker/caddy/Caddyfile

fix: error message : run: adapting config using caddyfile: /etc/caddy/Caddyfile:5: unrecognized global option: servers
https://caddyserver.com/docs/caddyfile/options

fix: Caddy error message servers

---

docker-compose.override.yml

This comment seems to got wrong over time:
The config made sense first: https://github.com/dunglas/symfony-docker/commit/df6286b2e91213100ff36dae25c8fac6384ef804#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3
Then the config became obsolete: https://github.com/dunglas/symfony-docker/commit/4e258087dc131307e84f95a5020db553259eb063
Then the config became a (I think wrong) comment: https://github.com/dunglas/symfony-docker/commit/0167334910d6f7c56c9dc9d68c9773dd35207ef3#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3
I don't use Mac so I don't know but maybe the whole comment could be removed completely since the `cached` option was introduced.

Fix comment and add another comment

---

docs/extra-services.md

Fixes #147. Messenger now uses Postgres by default through Doctrine, which is also supported by symfony-docker.

docs: remove Messenger from the list of supported packages

---

README.md

Similar to https://github.com/api-platform/docs/pull/1380

docs: add docker-compose build

---

docs/xdebug.md

docs: fix typo in xdebug.md docs

---

docker/php/docker-entrypoint.sh

IMHO always running composer install in PHP entrypoint is wrong.
In production this will:
* Install also dev dependencies which should not be installed
* Slow the starting phase of the container and this in turns increase the deployment downtime
So assume that in production the container runs from the image built with the Dockerfile, run composer install in entrypoint is wrong.

Fix: Do not run composer install in prod

---

docker/php/docker-entrypoint.sh

At time of writing, if you clone and create a new project, the PHP container will use PHP 8.0, but the composer.json file will specify >=7.2.5, this makes them the same.

Sync Docker and composer PHP versions in new projects

---

docker-compose.yml
docs/build.md

This might be useful if you have a less flexible HTTP server running on on you host.

feat: make HTTP ports variable

---

docker/php/docker-entrypoint.sh

The entrypoint only check whether there are PHP files in the `./migrations` directory but they can be generated in subdirectories when using the `BY_YEAR` or `BY_YEAR_AND_MONTH` configurations.

fix: check for migrations in subdirectories

---

docs/build.md

Because
```
symfony-docker-caddy-1  | {"level":"error","ts":1655149969.4670324,"logger":"tls.obtain","msg":"could not get certificate from issuer","identifier":"symfony.wip","issuer":"acme.zerossl.com-v2-DV90","error":"HTTP 400 urn:ietf:params:acme:error:rejectedIdentifier - Invalid DNS identifier [symfony.wip]"}
symfony-docker-caddy-1  | {"level":"error","ts":1655150030.459003,"logger":"tls.obtain","msg":"could not get certificate from issuer","identifier":"symfony.wip","issuer":"acme-v02.api.letsencrypt.org-directory","error":"HTTP 400 urn:ietf:params:acme:error:rejectedIdentifier - Error creating new order :: Cannot issue for \"symfony.wip\": Domain name does not end with a valid public suffix (TLD)"}
symfony-docker-caddy-1  | …
```

Replace unsupported wip tld by localhost

---

Dockerfile

The latest official php images [are now based on Alpine 3.16](https://hub.docker.com/_/php?tab=tags&page=1&name=8.1-fpm-alpine), which ships with ICU 71.1 (vs 69.1 in Alpine 3.15).
This breaks date & currency formatting, since only english locale is now included by default.
> _The ICU data [has been split](https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.16.0#ICU_data_split) into [icu-data-en](https://pkgs.alpinelinux.org/packages?name=icu-data-en) (default) and [icu-data-full](https://pkgs.alpinelinux.org/packages?name=icu-data-full) packages. Users may need to install icu-data-full for non-English locales or legacy charset converters support._
[(source)](https://alpinelinux.org/posts/Alpine-3.16.0-released.html)

fix: alpine 3.16 support for `ext-intl`

---

docker-compose.override.yml

Flags like :delegated, :cached and :ro don't exist anymore
See https://github.com/docker/for-mac/issues/5402

feat : remove deprecated flags

---

docker-compose.override.yml

Added commented lines in _docker-compose.override.yml_ about improving performance on Windows by using Docker volumes for the vendor and var directories.
Information found in issue #242.

Windows performance hint

---

docs/troubleshooting.md

Added information about how to add the caddy cert to the trusted certificates on Windows as this info was only provided for Linux & Mac.
_Note:_ I'm not using the same "docker cp $(docker compose ps -q caddy)" syntax as this does not work in the standard command prompt on Windows and as far as I know there is no equivalent.

docs: trust certificate on Windows

---

Dockerfile
docker-compose.override.yml
docker-compose.prod.yml
docker/php/conf.d/symfony.dev.ini
docker/php/conf.d/symfony.ini
docker/php/conf.d/symfony.prod.ini
docker/php/docker-entrypoint.sh
docs/xdebug.md

Closes https://github.com/dunglas/symfony-docker/issues/202.
Also simplifies the project.

feat: add native Xdebug support

---

docker/caddy/Caddyfile

> Caddy now enables [RFC 9114](https://datatracker.ietf.org/doc/rfc9114/)-compliant HTTP/3 by default. The experimental_http3 option has graduated and been removed.
https://github.com/caddyserver/caddy/releases/tag/v2.6.0

fix: stop use obsolete experimental_http3 option

---

Dockerfile

A new lighter image with only the Composer binary is available : https://github.com/composer/docker/pull/250

Using the new binary-only image from Composer

---

Dockerfile

Remove build args (as official images) and use the new installation method for `mlocati/php-extension-installer`.

chore: remove build args

---

docs/makefile.md

Current makefile template in docs/makefile.md is using equal sign when declaring .PHONY, this will be ignored because supposedly the correct syntax is using colon (:).

docs: use correct .PHONY syntax with colon (:)

---

docker/caddy/Caddyfile

Server Push has been removed from Chrome and this Caddy directive is known to cause issues in some cases (it has already been removed from API Platform).

chore: disable Caddy's push directive

---

docker-compose.yml

Added `charset` to `DATABASE_URL` in `docker-compose.yml`.
Defaults to `utf8`.
As per [this comment](https://github.com/dunglas/symfony-docker/issues/370#issuecomment-1407709869)

Add charset in docker-compose.yml

---

Dockerfile

Formatted dev PHP extensions list to keep same code style with prod one.
Found it useful when added new extension to the list:
```Dockerfile
RUN set -eux; \
install-php-extensions \
xdebug \
xhprof \
;

Format dev PHP extensions as prod

---

Dockerfile

There was an indentation with 4spaces that made vim edition look weird.

Fix indentation in Dockerfile

---

docker-compose.yml

In the 2.8 doctrine bundle recipes the default Postgres version is 15 so let's keep in sync with it.
See: https://github.com/symfony/recipes/blob/356ad033b1740ad32c780d050c2bf0ee128a3ca4/doctrine/doctrine-bundle/2.8/manifest.json#LL16C87-L16C89

Upgrade Postgres default version to 15

---

docker/php/php-fpm.d/zz-docker.conf

Backport of https://github.com/api-platform/api-platform/pull/2404, from @beerfranz.
Relies on the feature introduced in https://github.com/php/php-src/commit/327bb219867b16e1161da632fba170f46692484b.

feat: suppress Docker healthcheck requests from logs

---

Dockerfile

Use `COPY --chmod` instead of `COPY` + `RUN chmod`.
This removes two layers and reduce overall image size.

Set chmod in COPY instructions for docker scripts

---

Dockerfile

Not needed now that we use FrankenPHP.

chore: remove useless fgci package

---

frankenphp/docker-entrypoint.sh

fix: install Composer dependencies if vendor directory is empty

---

docs/extra-services.md
docs/production.md
docs/tls.md

The commands were pointing to a `docker-compose.yml` file that doesn't exist. It's `compose.yaml` now.

docs(production): fix command to run containers

---

docs/makefile.md

I've added the `test` target in the makefile template in order to remember to add the `APP_ENV=test` before the `phpunit` command.
I'm not sure to use the correct letter : `c` for adding options to `phpunit` : 
- pros : the same letter is used for `composer` and `sf` targets
- cons : `o` would be more appropriate since it passes options to `phpunit` and not command

Update makefile template

---

Dockerfile
frankenphp/conf.d/app.ini

Closes #555, #537.
Maybe could we even explain how to switch to Alpine in a documentation entry? It's super easy.

feat: switch to Debian instead of Alpine

---

docs/existing-project.md

With the new instructions the copying to an existing project doesn't destroy the cloned symfony-docker repository.

Added Git specific instuctions for copying the files to an existing project

---

compose.yaml
docs/tls.md

Fix issue with invalid `TRUSTED_HOSTS` and `MERCURE_PUBLIC_URL` when using `http://localhost` or `:80` as `SERVER_NAME` value
Follow up of https://github.com/api-platform/api-platform/pull/2666
Should I add a note in the docs @dunglas?

Introduce TRUSTED_HOSTS and CADDY_MERCURE_PUBLIC_URL variables

---

README.md

Added a clarification note to README.md to inform users how to set up a Symfony Flex application using the `docker compose up --pull always -d --wait` Docker command. This additional information provides clearer guidance for users looking to set up the application.

Update README with Symfony set up hint

---

docs/mysql.md

The install of doctrine-bundle adds a healthcheck section that was not documented.
Of course, GitHub CI was failing with an unhealthy status because of the PostgreSQL command. 
Update the documentation on how to use MySQL.

Update the documentation to change from PostgreSQL to MySQL.

---

compose.override.yaml

With the fix to load app's ini files after all other extensions are loaded (#617), the app-dev.ini file has been renamed 20-app.dev.ini and has been moved to a folder named "app.conf.d".
Although, the fix forgot to update the development environment file `compose.override.yaml` with the new name and location.

Fix Docker development volumes location for the 20-app.dev.ini file

---

Dockerfile

> We recommend using `docker/dockerfile:1`, which always points to the latest stable release of the version 1 syntax, and receives both "minor" and "patch" updates for the version 1 release cycle. 
<https://docs.docker.com/build/buildkit/frontend/>

chore: do not specify minor version of Dockerfile syntax

---

frankenphp/Caddyfile

Expanded, the current config is similar to this:
```caddyfile
@canonicalPath {
file {path}/index.php
not path */
}
redir @canonicalPath {path}/ 308
@indexFiles file {
try_files {path} {path}/index.php index.php
split_path .php
}
rewrite @indexFiles {http.matchers.file.relative}
@phpFiles path *.php
php @phpFiles
file_server
```
I recently took some time to profile and optimize FrankenPHP, and that config is the slowest part in FrankenPHP (this likely affects the `php_fastcgi` Caddy directive as well). All the calls to `try_files` and `file` do I/O operations, which are slow.
Most of these I/O operations are checks useful for traditional PHP apps where the document root contains a lot of `.php` files (like WordPress) but are not needed when using Symfony or Laravel.
This simplified config …

perf: improve FrankenPHP config

---

.github/workflows/ci.yml
frankenphp/Caddyfile

fix: do not handle requests to Mercure as PHP routes

---

frankenphp/docker-entrypoint.sh

**Problem statement :**
When running docker compose, for a few seconds / minutes, the container is running according to Docker, but in fact `docker-entrypoint.sh` is still downloading composer requirements and handling migrations. During this time, the app is not available. This means functionnal tests will fail if launched too early.
**Solution proposed :**
This pull requests aims to simply add a logging line at the end of `docker-enntrypoint.sh`, to provide a standard log that can be watched by dev / devops teams. A `grep` on docker logs will make people aware that : "ok, dependencies should be installed by now, so my app should be working".

feat: print message when docker-entrypoint finishes

---

compose.yaml

This PR adds the port to the Mercure public URL.
When using custom HTTPS port, the public url cannot be fetched as it becomes incorrect.

Add port to the Mercure Public URL

---

frankenphp/docker-entrypoint.sh

Currently, if there are errors that prevent the project from initializing correctly, the php container console shows a database connection error (see https://github.com/dunglas/symfony-docker/issues/718).
With this PR, I propose adding a check to ensure that the project can be initialized before checking the database connection. This will allow you to see a specific error in the php container console.

Added project initializability check in `docker-entrypoint.sh`

---

.github/workflows/ci.yml

---
I encountered an error in one of my private repositories based on the Symfony Docker template. The issue occurred when using `docker/bake-action < v5` with `buildx >= 0.20.0`.
Updating `docker/bake-action` from `v4` to `v6` resolved the issue.
- Updated `docker/bake-action` version in the workflow file from `v4` to `v6`.
- Verified that the workflows now run successfully without errors.

Update docker bake action to v6

---

.editorconfig
docs/makefile.md

Add indent style to tabs when editing Makefiles.
Makefiles does not work with spaces.

fix (Makefile): Configure editor to use tabs by default

---

docs/production.md
docs/troubleshooting.md

Due to issues #745 (probably) and #751 (and some seens on StackOverflow also), I propose to be a little more precise about the building of production images.

doc: add information about building production image

---

frankenphp/Caddyfile

Due to https://github.com/dunglas/mercure/pull/939 and the deprecation message, it makes sense to apply the Mercure configuration changes.
See:
- [Upgrade notice](https://github.com/dunglas/mercure/blob/main/docs/UPGRADE.md#017)
- [Original patch](https://github.com/dunglas/mercure/pull/939/commits/114044ee0fb80ebcb89c9f1f435a7f9fc422b911#diff-1f38639fad43624b85cdc2cac1778918713a061084bca6487683ec73f2b29fea)

Update Mercure configuration in Caddyfile

---

Dockerfile
compose.override.yaml
frankenphp/Caddyfile
frankenphp/worker.Caddyfile

Use the new "watcher" feature of FrankenPHP 1.4 to enable the worker mode in dev. Workers are automatically restarted when a file change.

feat: enable workers in dev (watchers)

---

Dockerfile

fix: do not use non-existent FrankenPHP worker config file

---

Dockerfile

After https://github.com/dunglas/symfony-docker/pull/766 the path for Mercure became `./bolt.db`, ​​which is different from what it was before (`/data/mercure.db`). This PR reverts the path back to the previous value.

Add default value of the `MERCURE_TRANSPORT_URL` in Dockerfile

---

README.md
docs/existing-project.md
docs/mysql.md
docs/options.md
docs/production.md
docs/tls.md
docs/troubleshooting.md
docs/xdebug.md
frankenphp/docker-entrypoint.sh

Part of #776
This PR brings the following commands to uniform formats:
* `docker compose ... build --pull --no-cache`
* The options are set in this order (this order was more common in this template).
* `docker compose ... up --wait`
* Specifying the `-d` option is optional (the `--wait` option implies the `-d` option, see https://github.com/dunglas/symfony-docker/issues/436#issuecomment-2792914977).
* `docker compose ... down --remove-orphans`
Already in a unified format.

chore: normalize docker compose commands

---

.editorconfig

Docker compose:
`compose.{yml,yaml}` and `docker-compose.{yml,yaml}` was not supported, fixed
Caddyfile:
`Caddyfile` was not supported, fixed

Fix .editorconfig to support Caddyfile and docker compose files

---

.github/workflows/ci.yml

Proposal of this change: https://github.com/dunglas/symfony-docker/pull/796#issuecomment-2939808993

chore(ci): Make the security downgrade of cURL requests more obvious

---

docs/alpine.md
docs/extra-services.md
docs/makefile.md
docs/mysql.md
docs/options.md
docs/tls.md
docs/troubleshooting.md
docs/xdebug.md

* `patch` code blocks are converted to `diff` (see https://github.com/dunglas/symfony-docker/pull/544#issuecomment-3245588974)
* Fixed indentation in `diff` code blocks
* Fixed several typos

chore: cleaning up the docs

---

Dockerfile
docs/alpine.md
frankenphp/docker-entrypoint.sh

I suggest removing the following dependencies:
- `acl`
- `gettext`
These dependencies are not used or have no useful functionality.
See https://github.com/dunglas/symfony-docker/discussions/819

deps: remove unnecessary dependencies
